In [2]:
import sqlite3 as sql
import pandas as pd

In [5]:
df = pd.read_csv('clientes.csv')
df.head()

,nome,email,idade,cidade,estado,data_ultima_compra,total_gasto,frequencia_compras,forma_pagamento,satisfacao,cliente_ativo
0,José Pereira,monteirocaua@example.com,56,da Mata de Minas,NJ,2024-01-01,1252.43,28,Débito,2,True
1,Luiz Felipe Siqueira,pedro-miguelgarcia@example.org,69,Novais,RS,2024-01-04,6476.55,30,Boleto,5,True
2,Gabriela Nunes,siqueiradavi-lucas@example.net,46,Araújo,SP,2024-01-07,6894.91,29,Débito,3,True
3,Fernando Teixeira,maria-vitoria55@example.net,32,Aparecida de Monteiro,RI,2024-01-11,5139.24,6,Débito,2,True
4,Srta. Lívia Rios,bentolopes@example.net,60,Guerra de Minas,PE,2024-01-14,6984.51,35,Boleto,3,True

In [7]:
banco = sql.connect(':memory:')
df.to_sql("clientes",banco,index=False,if_exists='replace')

150

In [11]:
dfsql = pd.read_sql_query("select * from clientes",banco)
dfsql.head()

,nome,email,idade,cidade,estado,data_ultima_compra,total_gasto,frequencia_compras,forma_pagamento,satisfacao,cliente_ativo
0,José Pereira,monteirocaua@example.com,56,da Mata de Minas,NJ,2024-01-01,1252.43,28,Débito,2,1
1,Luiz Felipe Siqueira,pedro-miguelgarcia@example.org,69,Novais,RS,2024-01-04,6476.55,30,Boleto,5,1
2,Gabriela Nunes,siqueiradavi-lucas@example.net,46,Araújo,SP,2024-01-07,6894.91,29,Débito,3,1
3,Fernando Teixeira,maria-vitoria55@example.net,32,Aparecida de Monteiro,RI,2024-01-11,5139.24,6,Débito,2,1
4,Srta. Lívia Rios,bentolopes@example.net,60,Guerra de Minas,PE,2024-01-14,6984.51,35,Boleto,3,1

In [15]:
dffiltro = pd.read_sql_query("select * from clientes where (idade > 30 and idade < 40)",banco)
dffiltro.head()
dffiltro.describe() #tras informacoes gerais

           idade  total_gasto  frequencia_compras  satisfacao  cliente_ativo
count  24.000000    24.000000           24.000000   24.000000      24.000000
mean   34.708333  4863.688333           21.166667    3.083333       0.541667
std     2.926330  2515.408277           11.373756    1.316011       0.508977
min    31.000000   345.970000            1.000000    1.000000       0.000000
25%    32.000000  2633.870000           11.500000    2.000000       0.000000
50%    34.500000  5015.990000           24.500000    3.000000       1.000000
75%    38.000000  7302.122500           31.000000    4.000000       1.000000
max    39.000000  8337.300000           37.000000    5.000000       1.000000