In [1]:
import requests
import pandas as pd

In [7]:
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv'
df = pd.read_csv(url, index_col='Month')
df.head()

       "1958"  "1959"  "1960"
Month
JAN       340     360     417
FEB       318     342     391
MAR       362     406     419
APR       348     396     461
MAY       363     420     472

In [18]:
url = r'https://catfact.ninja/facts'
resposta = requests.get(url)
dados = resposta.json()
dados.keys() #labels

fatos = dados['data']
df = pd.DataFrame(fatos)
df.head()

                                                fact  length
0  Unlike dogs, cats do not have a sweet tooth. S...     114
1  When a cat chases its prey, it keeps its head ...      97
2  The technical term for a cat’s hairball is a “...      54
3             A group of cats is called a “clowder.”      38
4  A cat can’t climb head first down a tree becau...     142